image: "rust:latest"

.run_test: &run_test
  script:
    - rustup update
    - rustup component add rustfmt clippy
    - rustup --version && rustc --version && cargo --version
    - time cargo fetch
    - cargo fmt --all --check --verbose
    - cargo clippy --workspace --all-targets --all-features -- -D warnings
    - cargo test --workspace --all-targets --all-features --verbose

# Use cargo to test the project
test:stable:
  <<: *run_test
  before_script:
    - rustup default stable

test:beta:
  <<: *run_test
  before_script:
    - rustup default beta

test:msrv:
  <<: *run_test
  before_script:
    - rustup default 1.61.0
