image: "rust:latest"

test:
  stage: test
  script:
    - export CARGO_UNSTABLE_SPARSE_REGISTRY=true
    - export CARGO_LOG=cargo::sources::registry::http_remote=trace
    - rustup toolchain install "$RUST_VERSION" --component rustfmt clippy
    - rustup install nightly
    - rustup default "$RUST_VERSION"
    - if [ "${DISABLE_CACHE:-false}" != "false" ]; then
    -     export CARGO_HOME="$CI_PROJECT_DIR/cargo"
    -     mkdir -p $CARGO_HOME target_cache
    -     ln -s /usr/local/cargo/bin $CARGO_HOME/bin
    -     ln -s /usr/local/cargo/env $CARGO_HOME/env
    -     ln -s target_cache target
    - fi
    - rustup --version && cargo --version
    - if [ "${USE_MINIMAL_VERSIONS:-false}" != "false" ]; then
    -     time cargo +nightly update -Z sparse-registry -Z minimal-versions
    - else
    -     time cargo +nightly update -Z sparse-registry
    - fi
    - cargo fetch
    - cargo fmt --all --check --verbose
    - cargo clippy --workspace --all-targets --all-features -- -D warnings
    - cargo test --workspace --all-targets --all-features
  cache:
    - key: "crates.io"
      paths:
        - cargo/bin/
        - cargo/registry/index/
        - cargo/registry/cache/
        - cargo/git/db/
    - key: "target"
      paths:
        - target_cache/
  paralell:
    matrix:
      - RUST_VERSION:
        - "stable"
        - "beta"
        - "nightly"
        - "1.65.0"
      - USE_MINIMAL_VERSIONS:
        - "false"
        - "true"
