image: "rust:latest"

.run_test: &run_test
  script:
    - rustup component add rustfmt clippy
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check
    - cargo clippy --workspace --all-targets --all-features --verbose -- -D warnings
    - cargo test --workspace --all-targets --all-features --verbose
  cache:
    - key:
        files: 
          - Cargo.lock
      paths:
        - target/
    - key: one-key-to-rule-them-all
      paths:
        # CARGO_HOME is /usr/local/cargo
        - /usr/local/cargo/bin/
        - /usr/local/cargo/registry/index/
        - /usr/local/cargo/registry/cache/
        - /usr/local/cargo/git/db/

# Use cargo to test the project
test:stable:
  <<: *run_test
  before_script:
    - rustup default stable

test:beta:
  <<: *run_test
  before_script:
    - rustup default beta
